apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: products-frontend 
  namespace: default 
spec:
  hosts:
  - products.demo.local
  gateways:
  - products-frontend 
  http:
  - route:
    - destination:
        host: products-frontend 