apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: guestbook-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: guestbook-frontend
        image: guestbook-frontend
        imagePullPolicy: Never
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 3000
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: $(BACKEND_SERVICE):8080