apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: guestbook-frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: guestbook-frontend
          imagePullPolicy: IfNotPresent