apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-mongodb 
spec:
  template:
    spec:
      containers:
        - name: guestbook-mongodb
          resources:
            limits:
              cpu: 1200m
            requests:
              memory: 300m 