---
# Source: dask/templates/dask-jupyter-config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dask-jupyter-config
  labels:
    app: dask
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: dask-3.1.0
    component: jupyter
data:
  jupyter_notebook_config.py: |
    c = get_config()
    c.NotebookApp.password = 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'



---
# Source: dask/templates/dask-jupyter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dask-jupyter
  labels:
    app: dask
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: dask-3.1.0
    component: jupyter
spec:
  ports:
    - name: dask-jupyter
      port: 80
      targetPort: 8888
  selector:
    app: dask
    release: "RELEASE-NAME"
    component: jupyter
  type: LoadBalancer



---
# Source: dask/templates/dask-scheduler-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  labels:
    app: dask
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: dask-3.1.0
    component: scheduler
spec:
  ports:
    - name: dask-scheduler
      port: 8786
      targetPort: 8786
    - name: dask-webui
      port: 80
      targetPort: 8787
  selector:
    app: dask
    release: "RELEASE-NAME"
    component: scheduler
  type: LoadBalancer

---
# Source: dask/templates/dask-jupyter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-jupyter
  labels:
    app: dask
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: dask-3.1.0
    component: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      release: "RELEASE-NAME"
      component: jupyter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "RELEASE-NAME"
        component: jupyter
    spec:
      imagePullSecrets:
        null
        
      containers:
        - name: dask-jupyter
          image: "daskdev/dask-notebook:1.1.5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          resources:
            {}
            
          volumeMounts:
            - name: config-volume
              mountPath: /home/jovyan/.jupyter
          env:
            - name: DASK_SCHEDULER_ADDRESS
              value: dask-scheduler:8786
      nodeSelector:
        {}
        
      volumes:
        - name: config-volume
          configMap:
            name: dask-jupyter-config

---
# Source: dask/templates/dask-scheduler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-scheduler
  labels:
    app: dask
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: dask-3.1.0
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      release: "RELEASE-NAME"
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "RELEASE-NAME"
        component: scheduler
    spec:
      imagePullSecrets:
        null
        
      containers:
        - name: dask-scheduler
          image: "daskdev/dask:1.1.5"
          imagePullPolicy: IfNotPresent
          args:
            - dask-scheduler
            - --port
            - "8786"
            - --bokeh-port
            - "8787"
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            {}
            
          env:
            null
            

---
# Source: dask/templates/dask-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-worker
  labels:
    app: dask
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: dask-3.1.0
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dask
      release: "RELEASE-NAME"
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "RELEASE-NAME"
        component: worker
    spec:
      imagePullSecrets:
        null
        
      containers:
        - name: dask-worker
          image: "daskdev/dask:1.1.5"
          imagePullPolicy: IfNotPresent
          args:
            - dask-worker
            - dask-scheduler:8786
            - --no-bokeh
          ports:
            - containerPort: 8789
          resources:
            {}
            
          env:
            null
            

---
# Source: dask/templates/dask-jupyter-ingress.yaml

---
# Source: dask/templates/dask-scheduler-ingress.yaml

