apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
  # - name: revision
  #   value: master
  - name: url
    value: https://github.com/castlemilk/kubernetes-cicd
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image 
spec:
  type: image
  params:
  - name: url
    value: gcr.io/kubernetes-cicd-246207/demo/backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: webhook-update-status
spec:
  inputs:
    resources:
    - name: image
      type: image
  steps:
  - name: message 
    image: golang
    env:
    - name: GOPATH
      value: /workspace/go
    command:
    - echo
    args:
    - "pass"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: webhook-build-push
spec:
  inputs:
    resources:
      - name: workspace
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/workspace/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/workspace
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    env:
    - name: "DOCKER_CONFIG"
      value: "/builder/home/.docker/"
    command:
      - /kaniko/executor
    args:
      - --dockerfile=${inputs.params.pathToDockerFile}
      - --destination=${outputs.resources.builtImage.url}
      - --context=${inputs.params.pathToContext}
      - --cache=true
      - --cache-repo=${outputs.resources.builtImage.url}
      - --insecure
---

---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: webhook-pipeline
spec:
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build-backend 
    taskRef:
      name: webhook-build-push
    params:
      - name: pathToDockerFile
        value: /workspace/workspace/app/backend/Dockerfile
      - name: pathToContext
        value: /workspace/workspace/app/backend
    resources:
      inputs:
      - name: workspace
        resource: git-source 
      outputs:
      - name: builtImage
        resource: docker-image
  - name: update-status 
    runAfter:
    - build-backend
    taskRef:
      name: webhook-update-status
    resources:
      inputs:
      - name: image
        resource: docker-image
        from:
        - build-backend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: webhook-pipeline-run-1
spec:
  serviceAccount: 'default'
  pipelineRef:
    name: webhook-pipeline
  resources:
  - name: git-source
    resourceRef:
      name: git-source
  - name: docker-image
    resourceRef:
      name: docker-image