apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: products-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: products-backend 
        image: products-backend
        imagePullPolicy: Never
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 3000
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCTS_DB_URL
          value: $(POSTGRES_SERVICE):5432
