bases:
- ../../backend/base
- ../../frontend/base
- ../../postgres/overlays/local
patchesJson6902:
- target:
    group: ''
    version: v1
    kind: Service
    name: postgres 
  path: service_patch.yaml
- target:
    group: ''
    version: v1
    kind: Service
    name: products-frontend
  path: service_patch.yaml
- target:
    group: ''
    version: v1
    kind: Service
    name: products-backend
  path: service_patch.yaml