bases:
- ../../backend/base
- ../../frontend/base
- ../../postgres/overlays/local
resources:
- namespace.yaml
namespace: development
vars:
- name: POSTGRES_SERVICE
  objref:
    kind: Service
    name: postgres
    apiVersion: v1
patchesJson6902:
- target:
    group: ''
    version: v1
    kind: Service
    name: postgres 
  path: service_patch.yaml
- target:
    group: ''
    version: v1
    kind: Service
    name: products-frontend
  path: service_patch.yaml
- target:
    group: ''
    version: v1
    kind: Service
    name: products-backend
  path: service_patch.yaml