---
# Source: opa/templates/webhookconfiguration.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa
  annotations:
  labels:
    app: opa
    chart: "opa-1.12.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
webhooks:
  - name: webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore
      

    failurePolicy: Ignore
    rules:
      - apiGroups:
        - '*'
        apiVersions:
        - '*'
        operations:
        - '*'
        resources:
        - '*'
      
    clientConfig:


      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQWR1Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFiTVJrd0Z3WURWUVFERXhCdmNHRXQKWVdSdGFYTnphVzl1TFdOaE1CNFhEVEU1TVRFd09UQXpNamMxT1ZvWERUSTVNVEV3TmpBek1qYzFPVm93R3pFWgpNQmNHQTFVRUF4TVFiM0JoTFdGa2JXbHpjMmx2YmkxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFPQlNycTFMa0RMUDVzVEJTYUdWa0tUWlZ3N3JzUVN6ZFY3OUxkZGRHR0xYUGJHblNic3kKbFJiQ0xIWHZXSkZhS3NrUFZuNnhPSjBld0RUZGdOcmV1R1pIZVMzS1UwUitBdjNZNWdwc1RTT1YxU3NUQWYzbQpDZ21yKzRFdi9HWVVmRlRHeFovK0Vua0lkNU1sdDJwL3FSc1ZhOVdDTURKT2lzODFlUVo2UDNvdy9FNi92UGlDCnBZVVFpNEJNRVdVcVdMbXlWem84SUJCNjFNRWlHMkVhRTlTYzZqZk42NUJ4QTdpQ1FWdStOcUtCdi9OMmxzYXgKYVF1ZDlBRkpUWGF3VlBWOUxBTUs1QVd2UURsc3VtUjY0VGU5UmQ5TkF0UFV0N0NvRHMvNkY2aUdMZDJKYjk2TApPSDJPK29OaFh1MWJDSXNwak40ZFdmVUFiVUFoTXdCOFlwTUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFECkFnS2tNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2JUY0tUM20wcm03em1YcllaRkxHVHk0dkJEMHZOZ014LwpIQkVXd29SK21reno0SVRic1AvNjdkM1djbXM5SHljdmh6dzQyYlQ3OC9mM0UvdkhhbmQrb1Nvb3VkbFdtWlIwCnhVU0o5UC91YWhGaHd4TnJPak1nc1I0eTVYZXhoTHUzdWtqUVJvajkvTmk1N0YvM3hOdTJTcmVXVFBtTy9oajkKUmgyNzRVYXp2Z1BYMG02bG5mTkFZSE9IZENRMWdadUw4ZGR3YzhBdkNoWGFNRTZwOTFVRlJxbHgzTlc3dkhzaAp5SDFyYTVjbjNqL3JiL3VpQ0o5V2NTQ09YbkN2OWUxMDZ0b09rUjFYUk8yOHF0RkZTNGtiOEZnUE5GWGxaZWhiCnJRclNwcERIMmJTU2RWci95U2RhSzJzWkVYbkpvc3g1RFlWcHdMZFd2MTlrbzZhSFdoZVgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=


      service:
        name: opa
        namespace: opa
    sideEffects: Unknown



---
apiVersion: v1
kind: Secret
metadata:
  name: opa-cert
  labels:
    app: opa
    chart: "opa-1.12.0"
    release: "RELEASE-NAME"
    heritage: "Tiller"
type: Opaque
data:

  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2ekNDQWRPZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFiTVJrd0Z3WURWUVFERXhCdmNHRXQKWVdSdGFYTnphVzl1TFdOaE1CNFhEVEU1TVRFd09UQXpNamMxT1ZvWERUSTVNVEV3TmpBek1qYzFPVm93RmpFVQpNQklHQTFVRUF4TUxiM0JoTG05d1lTNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNvSTI2cFhCbHdJcGJ0NlZ6NXN4WXdXZjVDcGltN3lMTGNzcHRxQktoK3cvZnRKc2tXTEdhcXQ0Z3gKM2FBNFUwalFaWHNIY1luQ3VBSThubzBnc3o4dms2cUxxaEY3eWhhSVdpVHNxK0RDVFoyeTlQeWVNdkxpNHZJUwpROHFNR2RjcGVsU1c4VUVHUG51QjQrbzlXMUU5L1BjZnlrUTFKT3kzV1dOMWxsdjJSdkdEaGtoMFlldXlXcmd0CmZyNk82YzErZlExR3VhcVd2ZEJ6NmlWYXM4Ky9raC9KTXZ2Qm9WUGlhdkE3Y256RlBrNy9jTXAyamZzTVlRYzYKOU9HQjFnUU9wRGhrSDRPUTh4dWpKUXZPcm52dUlsTWNZWE81cE5VQVZHWHpEck05eHdIZGJFZklLZXpKcjdGOAp5UXVxWTlrdE5BdkRLdkZpWjlBd1FPZUYwbEVwQWdNQkFBR2pQekE5TUE0R0ExVWREd0VCL3dRRUF3SUZvREFkCkJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVEFRSC9CQUl3QURBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFHSzJKMStUSGNzWGFodDZlRHBHOS9SRzJRemVUanpsVUNjMVVGNUhGN3E5RQpGcTVlalpwMnFuKzZYdlZRY0ZCVlB5NFdTNnkrTVI3cjdsVzdFcTczKzQvakxwM05pc29OaGYrd2NZL1lkcXNXCjJ2eUJiVTNnc3FCQjJYelU3UDU5dW5TajlRSDR2OGQwRktGWDFBV1pMN1VoaXRJZlhhbUlUSXI0d2xVaGhnYloKa004RWdzVGQ1RENzYjQ3ZForZWNreEMvUTJZTVk1YURvWTdhNEpiZk9yMEdISy9lZWVJVTNEREhMRXhQeVVQTQpmc2J2NUtZOTVqZTBCbEVMZlBvZ24zK1JIZmR3V2xTeHpDSnhZWDRxY25ta1BSOERDcFlEclF1b2ZFa2RjTFpXCm1Md3BEZlFEd2szK0tVNlBKK0l6TzJxRjU4U0M5U1Jka2JlaE5PMDltdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcUNOdXFWd1pjQ0tXN2VsYytiTVdNRm4rUXFZcHU4aXkzTEtiYWdTb2ZzUDM3U2JKCkZpeG1xcmVJTWQyZ09GTkkwR1Y3QjNHSndyZ0NQSjZOSUxNL0w1T3FpNm9SZThvV2lGb2s3S3Znd2syZHN2VDgKbmpMeTR1THlFa1BLakJuWEtYcFVsdkZCQmo1N2dlUHFQVnRSUGZ6M0g4cEVOU1RzdDFsamRaWmI5a2J4ZzRaSQpkR0hyc2xxNExYNitqdW5OZm4wTlJybXFscjNRYytvbFdyUFB2NUlmeVRMN3dhRlQ0bXJ3TzNKOHhUNU8vM0RLCmRvMzdER0VIT3ZUaGdkWUVEcVE0WkIrRGtQTWJveVVMenE1NzdpSlRIR0Z6dWFUVkFGUmw4dzZ6UGNjQjNXeEgKeUNuc3lhK3hmTWtMcW1QWkxUUUx3eXJ4WW1mUU1FRG5oZEpSS1FJREFRQUJBb0lCQUhMd2Jkakd4Zmo3SEZRZApJRnJ1Q3ZBWXhSREl5R1MvaVU0SHB1aHRzTVdmcjU5bDBUY2dPVHJnNWZDNHdhdGZlN3BDZFQwY1o0RStDd0ZuCm5iQkorSnJNaGx5ZGNRQS9vUEdyTmV5NGZwZzFPT1c2UmVyYmgyQ0VwZGpJa1BEL1JTL3NtV0RxSVhwa1FrZ0UKQnYvVXFoQUhHdVNYZjlNWW45Mmk5TFBRaXFNcXRuOHEwM1FSR1hzU2I0VXU4Ni9nR0I1SldsSUpHbzRxQlhsWQpPYzlDRWx5RTRScnVDajgza1FxSkVUaVVUb3ZUamwwaGY3MmpNWWxRR1B4d3RXTHc3TjFoTWhVVTh5T3JkN0piCjNwNitXSG8yMGpuTzhRVEpyTUhRc2tsV2lzd2V1Uys3WDVkMzRjZnZGanhGU0FhMlVBQ1FCQ1dQbXgzN1FrdG0KWCtVV2x3RUNnWUVBeTJsc2lrdlRlR1pPVmhTdUtoTHJOQlhRcjI1aVVaWkxOSmtPL1N4MlhYakM4Q1lCUURhcQp1eUhSeW0rK0NmMXVGaXdaT3FaRFNyekR0bTBueWlrVEY4ci95ZTFTNlFBWGlOdWhEbVB1TGtJeTE1aUp1dmVmCloxTEtodmt5SENpWlZ1bWNXa3U4d2M3T1gwS0YwM055QUZsRzFHVFBydk5Pc29ZL29EVEpxK0VDZ1lFQTA1dDYKaXZYT1RCalNTTEduaE5FdXRQQUJObkFpcU9WRWttaEZrNWtyZEdZZHBqcnUweEovbW9SMk9WNWxUbnBMWlRFcgpWelBqME5QTzFUUWUzNHRVZHJBZW1uQktabExQVmxZREZDQ1U1RVZScEx1ODAzNzVHQnNHWXp4WXpjTndxaDhKCllFQUdhNUYwWnhVTWpQQkF2KzBleUZWZW1USEVFZ3NlZHY0cURra0NnWUIyU25pMGRDUW1nRmhOOXZqUnZ1N0kKKzJiQW5wRE9vWGhhdmlmWlUySUNPWmdqei9ZcVFhQkg4d0x0bHM0TlFUUWo4TUU3T2pVbjRWNXZXRXNyWlhlVQovcGlCOVdHaDNrdlJhdWZlVm43TXAvS3BMaXZxYnRaa1grRW5YUU9uSEhVUDlnclc5L1J0UUxjQzdzeWtpeDVnCjFZbzdPZVVNK0xGcllHYmY0OUxrQVFLQmdRQ2JIQUhVY0YrYXlpc0NIQzhtSFV0MlYrTWJxMURNcXRuNzA3RUUKZ3ljbU9HQU5aRytCaXJLOGFkSmJOUVZmWkNkMThuZkpnUURDSnpBYWVnMFRZWWMxUk4zNTZNdXdlNHo5eFNpVwpqVmQyaUJWVGdrWGtaZE5qUnhRRWs4eW9iMVZiYmtxcUllUlMzeGtMSXBQRGo2eDJ3dkpvZUtOUitmZTJIaTVqCm5PVG8rUUtCZ0VUVmRnN25ZTFpxYytPK3k5blVoRzlMM3B4WjBrL2Uvc0oycDdrSnhYVkFSTVdjNVJ0bzdMTDcKSG9hdGR6Wm9xbklDRTdqOExOUzdKUStxZHRieWNSNGZTUzhDOWJMVXFEdGVMeUZ6NlFzdGE4ZjZqNTkxU0MwegptNHdyZmlaMzFmd2o2Mzh0RzNRN1VZb2hsOVFnc1FwNldaUWdVRWtBbjlEUlQ1NDR0QVNlCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==



