apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: products-backend
      context: src/backend
    - image: products-frontend
      context: src/frontend
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  local: {}
test:
  - image: products-backend:latest
    structureTests:
    - ./src/backend/tests/structure_test.yaml
deploy: {}

profiles:
  - name: local-development
    deploy:
      kustomize:
          path: deploy/overlays/local
          flags:
            global:
            - '-n=development'
  - name: remote-development
    build:
      artifacts:
        - image: gcr.io/kubernetes-cicd-246207/dev/backend
          context: src/backend
        - image: gcr.io/kubernetes-cicd-246207/dev/frontend
          context: src/frontend
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:latest"
    deploy:
      kustomize:
          path: deploy/overlays/non-production
          flags:
            global:
            - '-n=np'
  - name: non-production
    deploy:
      kustomize:
          path: deploy/overlays/non-production
          flags:
            global:
            - '-n=np'
  - name: production
    deploy:
      kustomize:
          path: deploy/overlays/production
          flags:
            global:
            - '-n=prod'
  - name: ci-postgres
    build: {}
    deploy:
      kustomize:
        path: deploy/postgres/overlays/ci
        flags:
          global:
          - '-n=tekton-pipelines'
