apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: products-backend
      context: src/backend
    - image: products-frontend
      context: src/frontend
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  local: {}
test:
  - image: products-backend:latest
    structureTests:
    - ./src/backend/tests/structure_test.yaml
deploy: {}

profiles:
  - name: local-development
    deploy:
      kustomize:
          path: deploy/overlays/local
  - name: remote-development
    deploy:
      kustomize:
          path: deploy/overlays/non-prod
  - name: non-production
    deploy:
      kustomize:
          path: deploy/overlays/non-prod
  - name: ci-postgres
    build: {}
    deploy:
      kustomize:
        path: deploy/postgres/overlays/non-prod-ci
        flags:
          global:
          - '-n=tekton-pipelines'
