apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
    - image: products-backend
      context: src/backend
    # - image: products-frontend
    #   context: src/frontend
  tagPolicy:
    sha256: {}
deploy:

profiles:
  - name: local-development
    deploy:
      kustomize:
          path: deploy/overlays/local
