# This is used to generate minimal demo mode. It is included from demo and demo-auth values.
# It is shipped with the release, used for bookinfo or quick installation of istio.
# Includes components used in the demo, defaults to alpha3 rules.
# Note: please only put common configuration for the demo profiles here.
global:
  controlPlaneSecurityEnabled: true
  disablePolicyChecks: true
  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true
  proxy:
    disablePolicyChecks: true
    autoInject: disabled
    accessLogFile: "/dev/stdout"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
    accessLogFormat: ""
    # Configure the access log for sidecar to JSON or TEXT.
    accessLogEncoding: TEXT
  # enable pod distruption budget for the control plane, which is used to
  # ensure Istio control plane components are gradually upgraded or recovered.
  defaultPodDisruptionBudget:
    enabled: false
sidecarInjectorWebhook:
  enabled: true
  enableNamespacesByDefault: true
  # If true, webhook or istioctl injector will rewrite PodSpec for liveness
  # health check to redirect request to sidecar. This makes liveness check work
  # even when mTLS is enabled.
  rewriteAppHTTPProbe: true  
pilot:
  traceSampling: 0.50
  autoscaleMin: 1
  autoscaleMax: 1                                            
  resources:
    requests:
      cpu: 30m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 500Mi

mixer:
  policy:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi

  telemetry:
    enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
 
  adapters:
    stdio:
      enabled: true
    prometheus:
      enabled: false
 
grafana:
  enabled: false

tracing:
  enabled: false
prometheus:
  enabled: false

kiali:
  enabled: false
  createDemoSecret: false

gateways:
  istio-ingressgateway:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      name: http2
    - port: 443
      name: https
      targetPort: 443 
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: 100m
        memory: 128Mi

  istio-egressgateway:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: 100m
        memory: 128Mi
# This is used to generate istio-auth.yaml for minimal, demo mode with MTLS enabled.
# It is shipped with the release, used for bookinfo or quick installation of istio.
# Includes components used in the demo, defaults to alpha3 rules.