apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: tcp-postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/db-data
            - name: postgres-initdb-configmap
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: postgres-storage
          emptyDir: {}
        - name: postgres-initdb-configmap
          configMap:
            name: bootstrap-scripts