
namePrefix: local-
commonLabels:
  app: guestbook

bases:
- ../../backend
- ../../frontend
- ../../mongodb

vars:
  - name: MONGODB_SERVICE
    objref:
      kind: Service
      name: guestbook-mongodb
      apiVersion: v1
  - name: BACKEND_SERVICE
    objref:
      kind: Service
      name: guestbook-backend
      apiVersion: v1