apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-mongodb 
spec:
  template:
    spec:
      containers:
        - name: mongodb 
          resources:
            limits:
              cpu: 2200m
            requests:
              memory: 1000m 