apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: application-git-repo
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/castlemilk/kubernetes-cicd
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-frontend
spec:
  type: image
  params:
    - name: url
      # value: host.docker.local:5000/app/frontend
      value: registry.kube-system.svc.cluster.local/demo/frontend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-backend
spec:
  type: image
  params:
    - name: url
      # value: host.docker.local:5000/app/frontend
      value: registry.kube-system.svc.cluster.local/demo/backend
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-application
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/docker-source/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}
        - --cache=true
        - --insecure
---
# apiVersion: tekton.dev/v1alpha1
# kind: TaskRun
# metadata:
#   name: build-frontend
# spec:
#   taskRef:
#     name: build-application
#   trigger:
#     type: manual
#   inputs:
#     resources:
#       - name: docker-source
#         resourceRef:
#           name: application-git-repo
#     params:
#       - name: pathToDockerFile
#         value: /workspace/docker-source/app/frontend/Dockerfile
#       - name: pathToContext
#         value: /workspace/docker-source/app/frontend
#   outputs:
#     resources:
#       - name: builtImage
#         resourceRef:
#           name: frontend-image
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-backend
spec:
  taskRef:
    name: build-application
  trigger:
    type: manual
  inputs:
    resources:
      - name: docker-source
        resourceRef:
          name: application-git-repo
    params:
      - name: pathToDockerFile
        value: /workspace/docker-source/app/backend/Dockerfile
      - name: pathToContext
        value: /workspace/docker-source/app/backend
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: frontend-image