apiVersion: tektonexperimental.dev/v1alpha1
kind: EventBinding
metadata:
  name: backend-ci-binding
  namespace: default
  labels:
    app: backend-ci-binding
spec:
  # eventref:
  #   eventname: pushevents
  #   eventtype: dev.knative.source.github.push
  setBuildSha: "true"
  eventname: pushevents
  eventtype: dev.knative.source.github.push
  serviceAccount: backend-ci-binding-admin
  selector:
    matchLabels:
      app: backend-ci-binding
  template:
    metadata:
      labels:
        role: backend-ci-binding
  pipelineRef:
    name: backend-pipeline-ci
  sourceref:
    name: backend-pipeline-ci-source
  resourceTemplates:
  - name: demo-source-repo
    metadata:
      name: demo-source-repo
      namespace: default 
    spec:
      type: git
      params:
      - name: url
        value: https://github.com/castlemilk/kubernetes-cicd
      - name: revision
        value: master
  - name: backend-image 
    metadata:
      name: backend-image 
      namespace: default 
    spec:
      type: image
      params:
      - name: url
        value: registry.kube-system.svc.cluster.local/demo/backend