apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: dev-xp-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/castlemilk/NEXTgen-developer-experience
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: dev-xp-image
spec:
  type: image
  params:
    - name: url
      value: host.docker.local:5000/dev-xp/webapp