apiVersion: v1
data:
  example.rego: |-
    package example

    greeting = msg {
        info := opa.runtime()
        hostname := info.env["HOSTNAME"] # Kubernetes sets the HOSTNAME environment variable.
        msg := sprintf("hello from pod %q!", [hostname])
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: example-policy
  namespace: opa
  labels:
    openpolicyagent.org/policy: rego
    