apiVersion: v1
data:
  pod-registry.rego: |-
    package kubernetes.admission                                                # line 1

    deny[msg] {                                                                 # line 2
      input.request.kind.kind == "Pod"                                          # line 3
      image := input.request.object.spec.containers[_].image                    # line 4
      not startswith(image, "hooli.com/")                                       # line 5
      msg := sprintf("image '%v' comes from untrusted registry", [image])       # line 6
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: example-policy-2
  namespace: opa
  labels:
    openpolicyagent.org/policy: rego