apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: backend-pipeline-ci-admin
  namespace: default 
subjects:
  - kind: ServiceAccount
    name: backend-pipeline-ci-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: backend-pipeline-ci-admin
  apiGroup: rbac.authorization.k8s.io